In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r'C:\Users\user\OneDrive\Desktop\Data Science\Medical-Disease-Predicition-System\cleaned_md.csv')

In [4]:
df

,Unnamed: 0,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,0,23,1,17.5,102,177,161,88,0,0,2,0,1
1,1,69,1,31.1,118,256,147,92,0,0,0,1,4
2,2,61,0,31.3,114,206,193,74,1,0,2,0,1
3,3,47,0,23.9,105,162,253,68,0,0,1,0,1
4,4,47,1,28.3,148,121,280,84,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,49,1,27.1,177,183,268,59,0,0,0,0,3
9996,9996,84,1,29.2,142,215,145,77,0,1,0,1,3
9997,9997,41,1,22.8,177,265,133,71,0,0,2,1,3
9998,9998,55,1,29.0,126,241,298,57,0,0,2,1,4
9999,9999,59,1,32.2,151,162,225,93,0,0,0,1,4

In [5]:
df.drop('Unnamed: 0',axis =1,inplace =True)

In [6]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,1,17.5,102,177,161,88,0,0,2,0,1
1,69,1,31.1,118,256,147,92,0,0,0,1,4
2,61,0,31.3,114,206,193,74,1,0,2,0,1
3,47,0,23.9,105,162,253,68,0,0,1,0,1
4,47,1,28.3,148,121,280,84,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,1,27.1,177,183,268,59,0,0,0,0,3
9996,84,1,29.2,142,215,145,77,0,1,0,1,3
9997,41,1,22.8,177,265,133,71,0,0,2,1,3
9998,55,1,29.0,126,241,298,57,0,0,2,1,4
9999,59,1,32.2,151,162,225,93,0,0,0,1,4

In [7]:
x = df.drop('Disease', axis =1)

In [8]:
y  = df[['Disease']]

In [9]:
x

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory
0,23,1,17.5,102,177,161,88,0,0,2,0
1,69,1,31.1,118,256,147,92,0,0,0,1
2,61,0,31.3,114,206,193,74,1,0,2,0
3,47,0,23.9,105,162,253,68,0,0,1,0
4,47,1,28.3,148,121,280,84,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,49,1,27.1,177,183,268,59,0,0,0,0
9996,84,1,29.2,142,215,145,77,0,1,0,1
9997,41,1,22.8,177,265,133,71,0,0,2,1
9998,55,1,29.0,126,241,298,57,0,0,2,1
9999,59,1,32.2,151,162,225,93,0,0,0,1

In [10]:
y

      Disease
0           1
1           4
2           1
3           1
4           1
...       ...
9995        3
9996        3
9997        3
9998        4
9999        4

[10000 rows x 1 columns]

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 42,test_size = 0.2)

In [13]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((8000, 11), (8000, 1), (2000, 11), (2000, 1))

In [15]:
from sklearn.svm import SVC,SVR
sv = SVC()
sv.fit(x_train,y_train)

c:\Users\user\OneDrive\Desktop\Data Science\datascience\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC()

In [16]:
print(sv.score(x_train,y_train))
print(sv.score(x_test,y_test))

0.63125
0.6395

In [18]:
from sklearn.tree import DecisionTreeClassifier , DecisionTreeRegressor
dtc = DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [19]:
print(dtc.score(x_train,y_train))
print(dtc.score(x_test,y_test))

1.0
0.645

In [24]:
x_train

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory
9254,76,1,29.6,134,266,318,101,1,0,2,1
1561,35,0,29.3,96,220,300,58,0,0,1,0
1670,69,1,29.6,164,149,229,98,0,0,1,0
6087,47,1,29.0,159,250,258,109,0,1,2,0
6669,42,1,23.4,107,224,300,82,1,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...
5734,61,0,30.2,175,147,167,102,0,1,1,0
5191,79,0,20.5,150,225,142,84,0,0,2,1
5390,30,1,27.6,119,101,129,110,0,0,2,0
860,82,1,30.7,108,143,231,102,1,0,1,1
7270,38,1,17.3,176,89,284,66,0,1,0,1

In [25]:
y_train

      Disease
9254        3
1561        1
1670        1
6087        1
6669        1
...       ...
5734        4
5191        1
5390        1
860         3
7270        3

[8000 rows x 1 columns]

In [27]:
x_test

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory
6252,36,1,23.5,122,156,146,99,0,1,2,1
4684,52,0,23.0,147,137,273,107,0,0,0,0
1731,78,1,26.3,118,128,125,55,0,0,2,1
4742,46,1,22.6,161,211,147,59,0,0,1,0
4521,64,0,27.2,126,261,162,108,1,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...
6412,23,0,25.5,114,204,220,99,0,0,1,0
8285,20,1,32.3,131,257,287,77,0,0,1,0
7853,53,0,26.8,180,240,306,94,0,0,0,0
1095,23,0,35.2,118,148,292,100,0,0,1,0
6929,68,0,16.5,105,117,307,62,0,0,2,0

In [29]:
y_test

      Disease
6252        1
4684        1
1731        1
4742        1
4521        3
...       ...
6412        1
8285        1
7853        3
1095        1
6929        1

[2000 rows x 1 columns]

In [30]:
dtc.predict([[36,	1	,23.5	,122	,156	,146	,99	,0	,1	,2,	1]])

c:\Users\user\OneDrive\Desktop\Data Science\datascience\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [31]:
dtc.predict([[64	,0	,27.2	,126	,261	,162	,108	,1	,1	,2	,0]])

c:\Users\user\OneDrive\Desktop\Data Science\datascience\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([4])

In [26]:
y_pred = dtc.predict(x_test)

In [22]:
confusion_matrix(y_test,y_pred)

array([[  14,    0,   14,   15,    3],
       [   1, 1077,    4,   94,  103],
       [  14,    8,    6,   22,    3],
       [   9,  110,   18,  120,   99],
       [   2,   90,    7,   94,   73]])

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.645